/// Collectors module for gathering blockchain events
/// 
/// Provides different strategies for collecting events:
/// - Time-based polling for consistent intervals
/// - Block-based monitoring for real-time updates (planned)
/// - Pending transaction monitoring (planned)
pub mod collectors;

/// Executors module for handling bot actions
/// 
/// Manages the execution of actions generated by strategies,
/// including transaction submission and protection mechanisms.
pub mod executors;

/// Strategies module for trading logic
/// 
/// Contains the core liquidation strategy implementation
/// and related types for Aave V3 operations.
pub mod strategies;

/// Addresses module for contract address management
/// 
/// Provides centralized access to contract addresses
/// and deployment-specific configurations.
pub mod addresses;

/// Storage module for data persistence
/// 
/// Provides abstract storage interfaces and implementations
/// for borrower state and bot configuration persistence.
pub mod storage;
